server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /estoque/ {
        try_files $uri $uri/ /estoque/listafacil.html;
    }
    location /estoque/contagem.html {
        try_files $uri =404;
    }
    location /pdv/ {
        try_files $uri $uri/ /pdv/comandafacil.html;
    }
    location /rest/v1/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream SLUG-postgrest;
        rewrite ^/rest/v1/(.*)$ /$1 break;
        proxy_pass http://$upstream:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header apikey $http_apikey;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Accept application/json;
    }
}
