script: |
  cd /home/ubuntu/app

  git pull origin main

  cd traefik && docker compose up -d --build
  cd ../landing && docker compose up -d --build
  cd ../painel && docker compose up -d --build
  cd ../orchestrator && docker compose up -d --build
